POST http://localhost:8080/api/v1/users/save
Content-Type: application/json

{
    "firstName": "Kelly",
    "lastName": "Blue",
    "email": "kellyb@gmail.com",
    "password": "kellyblue",
    "role": "user"
}

###
POST http://localhost:8080/api/v1/users/save
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Red",
    "email": "johnr@gmail.com",
    "password": "johnred",
    "role": "user"
}

###
POST http://localhost:8080/api/v1/users/save
Content-Type: application/json

{
    "firstName": "Tom",
    "lastName": "Green",
    "email": "tomg@gmail.com",
    "password": "tomgreen",
    "role": "user"
}

###
POST http://localhost:8080/api/v1/users/signin
Content-Type: application/json

{
    "email": "johnr@gmail.com",
    "password": "johnred"
}

###
POST http://localhost:8080/api/v1/users/signin
Content-Type: application/json

{
    "email": "tomg@gmail.com",
    "password": "tomgreen"
}

###
POST http://localhost:8080/api/v1/users/signin
Content-Type: application/json

{
    "email": "kellyb@gmail.com",
    "password": "kellyblue"
}

###
GET http://localhost:8080/api/v1/getdata
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJQU04iLCJzdWIiOiJkYXZpZGJAZ21haWwuY29tIiwiaWF0IjoxNjQwNTQyNTM5LCJleHAiOjE2NDA2Mjg5Mzl9.5JawwMfRRDD-2SAFeksvSt_LAc5rT3zhm-4kbwR9JYHf8ravY9gRPFU4bL5stNss1_0xBsUmNvOUmJyCIjjBgw

###
GET http://localhost:8080/api/v1/users

###
GET http://localhost:8080/api/v1/users/61c83bc814313b1c882325c4

###
# make a post
POST http://localhost:8080/api/v1/insertpost
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJQU04iLCJzdWIiOiJrZWxseWJAZ21haWwuY29tIiwiaWF0IjoxNjQwNzc0NTM2LCJleHAiOjE2NDA4NjA5MzZ9.gDoJd-C35xe4TKt_QGtHpxa6OkRkfH-Ij9cam6en4VUUXrch4juTuoXvIXklwfGh7TqqSjyH_gUplHuGnVNelQ
Content-Type: application/json

{
    "id": null,
    "userId": "61cb456dcc98c61c22bc37d9",
    "content": "Kelly Blue third post is here",
    "createdAt": null,
    "love": null,
    "share": null,
    "comment": null
}

###
# comment a post
POST http://localhost:8080/api/v1/insertcomment
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJQU04iLCJzdWIiOiJrZWxseWJAZ21haWwuY29tIiwiaWF0IjoxNjQwNzEzNTM2LCJleHAiOjE2NDA3OTk5MzZ9.bI9eR0_Bny74qL5qusoXs8UZPPFSfc7xRNrLYV5hETtsRhP5kxTpM_bRK7V-X9zfrQZAHKu85QV4kRYRyq7pBQ
Content-Type: application/json

{
    "commentEntity": {
        "userId": "61cb456dcc98c61c22bc37d9",
        "content": "A comment from Kelly",
        "createdAt": null
    },
    "postId": {
        "id": "61cb490cbe444d78bf3a6451"
    }    
}

###
# love a post
POST http://localhost:8080/api/v1/lovepost
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJQU04iLCJzdWIiOiJrZWxseWJAZ21haWwuY29tIiwiaWF0IjoxNjQwNzUxMjI4LCJleHAiOjE2NDA4Mzc2Mjh9.yL0WJkClHtdIZQV9KfvyHExI0B3NX9TGxNCn4B2Th2cACPp0M_I0sG9V1f9oecDpuK6wYmSeVLlBuUI6Rber8g
Content-Type: application/json

{
    "id1": "61cb490cbe444d78bf3a6451",
    "id2": "61cb456dcc98c61c22bc37d9"
}

###
# share a post
POST http://localhost:8080/api/v1/sharepost
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJQU04iLCJzdWIiOiJrZWxseWJAZ21haWwuY29tIiwiaWF0IjoxNjQwNzUxMjI4LCJleHAiOjE2NDA4Mzc2Mjh9.yL0WJkClHtdIZQV9KfvyHExI0B3NX9TGxNCn4B2Th2cACPp0M_I0sG9V1f9oecDpuK6wYmSeVLlBuUI6Rber8g
Content-Type: application/json

{
    "id1": "61cb490cbe444d78bf3a6451",
    "id2": "61cb456dcc98c61c22bc37d9"
}

###
# follow someone
POST http://localhost:8080/api/v1/users/follow
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJQU04iLCJzdWIiOiJrZWxseWJAZ21haWwuY29tIiwiaWF0IjoxNjQwNzY3Nzk4LCJleHAiOjE2NDA4NTQxOTh9.h1J_eu8ipxU4SebsiSz375W_x8PgyY2KRl8YP7Ri4g_LvjhEHM4Y0bk1ydqhy2g29KI6K_HWQQ099IWJvXyohQ
Content-Type: application/json

{
    "id1": "61cbf7b3d2c64c62de758285",
    "id2": "61cb456dcc98c61c22bc37d9"
}

###
# get list of following users
GET http://localhost:8080/api/v1/users/getfollowing/61cbf7b3d2c64c62de758285
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJQU04iLCJzdWIiOiJrZWxseWJAZ21haWwuY29tIiwiaWF0IjoxNjQwNzY3Nzk4LCJleHAiOjE2NDA4NTQxOTh9.h1J_eu8ipxU4SebsiSz375W_x8PgyY2KRl8YP7Ri4g_LvjhEHM4Y0bk1ydqhy2g29KI6K_HWQQ099IWJvXyohQ

###
# get list of followers
GET http://localhost:8080/api/v1/users/getfollower/61cbf7b3d2c64c62de758285
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJQU04iLCJzdWIiOiJ0b21nQGdtYWlsLmNvbSIsImlhdCI6MTY0MDc2ODUyMywiZXhwIjoxNjQwODU0OTIzfQ.3Z31pyaqqoH_9r6ioWFTmKJpFdYADmtLaiYoXtSu2GjKUn_x_eGQTD-mLFdtTlt7BPq-DCwnX2-FQ7BPlucZpw

###
# get my own posts
GET http://localhost:8080/api/v1/myposts
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJQU04iLCJzdWIiOiJrZWxseWJAZ21haWwuY29tIiwiaWF0IjoxNjQwNzY3Nzk4LCJleHAiOjE2NDA4NTQxOTh9.h1J_eu8ipxU4SebsiSz375W_x8PgyY2KRl8YP7Ri4g_LvjhEHM4Y0bk1ydqhy2g29KI6K_HWQQ099IWJvXyohQ
Content-Type: application/json

{
    "id": "61cb456dcc98c61c22bc37d9"
}

###
# get posts from following users
GET http://localhost:8080/api/v1/followingposts
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJQU04iLCJzdWIiOiJrZWxseWJAZ21haWwuY29tIiwiaWF0IjoxNjQwNzY3Nzk4LCJleHAiOjE2NDA4NTQxOTh9.h1J_eu8ipxU4SebsiSz375W_x8PgyY2KRl8YP7Ri4g_LvjhEHM4Y0bk1ydqhy2g29KI6K_HWQQ099IWJvXyohQ
Content-Type: application/json

{
    "id": "61cb456dcc98c61c22bc37d9"
}
